# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLK]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]
 
# Switches (Using Switch 0 for Reset)
set_property PACKAGE_PIN V17 [get_ports RST]					
	set_property IOSTANDARD LVCMOS33 [get_ports RST]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property PACKAGE_PIN P3 [get_ports {LED[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property PACKAGE_PIN N3 [get_ports {LED[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property PACKAGE_PIN P1 [get_ports {LED[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property PACKAGE_PIN L1 [get_ports {LED[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]

# 7 segment display (Renamed to match SSEG_CAT and SSEG_AN)
# Segment Cathodes
set_property PACKAGE_PIN W7 [get_ports {SSEG_CAT[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[6]}]
set_property PACKAGE_PIN W6 [get_ports {SSEG_CAT[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[5]}]
set_property PACKAGE_PIN U8 [get_ports {SSEG_CAT[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[4]}]
set_property PACKAGE_PIN V8 [get_ports {SSEG_CAT[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[3]}]
set_property PACKAGE_PIN U5 [get_ports {SSEG_CAT[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[2]}]
set_property PACKAGE_PIN V5 [get_ports {SSEG_CAT[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[1]}]
set_property PACKAGE_PIN U7 [get_ports {SSEG_CAT[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[0]}]
set_property PACKAGE_PIN V7 [get_ports {SSEG_CAT[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_CAT[7]}]

# Anodes
set_property PACKAGE_PIN U2 [get_ports {SSEG_AN[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_AN[0]}]
set_property PACKAGE_PIN U4 [get_ports {SSEG_AN[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_AN[1]}]
set_property PACKAGE_PIN V4 [get_ports {SSEG_AN[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_AN[2]}]
set_property PACKAGE_PIN W4 [get_ports {SSEG_AN[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSEG_AN[3]}]
# Buttons
set_property PACKAGE_PIN U18 [get_ports BTN[0]]						
	set_property IOSTANDARD LVCMOS33 [get_ports BTN[0]]
set_property PACKAGE_PIN T18 [get_ports BTN[1]]						
	set_property IOSTANDARD LVCMOS33 [get_ports BTN[1]]
set_property PACKAGE_PIN W19 [get_ports BTN[2]]						
	set_property IOSTANDARD LVCMOS33 [get_ports BTN[2]]

## Configuration options, can prevent bitstream errors on some boards
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]